(yas/define-snippets 'css-mode
                     '(("bg" "background-color: #${1:DDD};" "background-color: ..." nil nil nil nil nil)
                       ("bg" "background-image: url($1);" "background-image: ..." nil nil nil nil nil)
                       ("bor" "border: ${1:1px} ${2:solid} #${3:999};" "border size style color" nil nil nil nil nil)
                       ("cl" "clear: $1;\n" "clear: ..." nil nil nil nil nil)
                       ("disp" "display: block;\n" "display: block" nil nil nil nil nil)
                       ("disp" "display: inline;\n" "display: inline" nil nil nil nil nil)
                       ("disp" "display: none;\n" "display: none" nil nil nil nil nil)
                       ("ff" "font-family: $1;\n" "font-family: ..." nil nil nil nil nil)
                       ("fs" "font-size: ${12px};\n" "font-size: ..." nil nil nil nil nil)
                       ("mar" "margin-bottom: $1;\n" "margin-bottom: ..." nil nil nil nil nil)
                       ("mar" "margin-left: $1;\n" "margin-left: ..." nil nil nil nil nil)
                       ("mar" "margin: $1;\n" "margin: ..." nil nil nil nil nil)
                       ("mar" "margin: ${top} ${right} ${bottom} ${left};\n" "margin top right bottom left" nil nil nil nil nil)
                       ("mar" "margin-right: $1;\n" "margin-right: ..." nil nil nil nil nil)
                       ("mar" "margin-top: $1;\n" "margin-top: ..." nil nil nil nil nil)
                       ("pad" "padding-bottom: $1;\n" "padding-bottom: ..." nil nil nil nil nil)
                       ("pad" "padding-left: $1;\n" "padding-left: ..." nil nil nil nil nil)
                       ("pad" "padding: $1;\n" "padding: ..." nil nil nil nil nil)
                       ("pad" "padding: ${top} ${right} ${bottom} ${left};\n" "padding: top right bottom left" nil nil nil nil nil)
                       ("pad" "padding-right: $1;\n" "padding-right: ..." nil nil nil nil nil)
                       ("pad" "padding-top: $1;\n" "padding-top: ..." nil nil nil nil nil))
                     'nil)